# Generated by Django 3.0.3 on 2020-03-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='niveau',
            field=models.CharField(default='sixieme', max_length=30),
        ),
    ]
