# Generated by Django 3.0.3 on 2020-03-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identite', '0002_eleve_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='eleve',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
