# Generated by Django 3.0.3 on 2020-03-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identite', '0004_auto_20200317_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='etablissement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='identite.Etablissement'),
        ),
    ]
