# Generated by Django 3.0.3 on 2020-03-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identite', '0005_auto_20200317_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='etablissement',
        ),
    ]
