# Generated by Django 3.0.3 on 2020-03-17 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identite', '0006_remove_eleve_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='etablissement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='identite.Etablissement'),
        ),
    ]
