# Generated by Django 3.0.3 on 2020-03-17 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('identite', '0007_eleve_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
