# Generated by Django 3.0.3 on 2020-03-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identite', '0008_auto_20200317_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=20)),
                ('distinct', models.CharField(blank=True, max_length=20)),
                ('serie', models.CharField(blank=True, max_length=3)),
            ],
        ),
    ]
